/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.funcionalidadcomprarmembresiausuarionoregistrado.presentacion;

/**
 *
 * @author Diego
 */
public class BeneficiosFORM extends javax.swing.JFrame {

    private ControlForms control;

    public BeneficiosFORM(ControlForms control) {
        this.control = control;
        this.setTitle("Beneficios");
        initComponents();
        ComboBoxMembresia.setFocusable(false);
        setearEditablesFalsosCheckBox();
        actualizarBeneficios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        btnPrecio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnTemporal = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        checkBoxCursos = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaCursos = new javax.swing.JTextArea();
        checkBoxMusica = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaMusica = new javax.swing.JTextArea();
        jSeparator5 = new javax.swing.JSeparator();
        checkBoxFisico = new javax.swing.JCheckBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaProgresoFisico = new javax.swing.JTextArea();
        jSeparator6 = new javax.swing.JSeparator();
        checkBoxInstalaciones = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaInstalaciones = new javax.swing.JTextArea();
        checkBoxNutricion = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaCentroNutricion = new javax.swing.JTextArea();
        lblPrecio = new javax.swing.JLabel();
        ComboBoxMembresia = new javax.swing.JComboBox<>();
        btnSuscribirse1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(18, 18, 18));

        btnPrecio.setBackground(new java.awt.Color(44, 44, 44));
        btnPrecio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPrecio.setForeground(new java.awt.Color(255, 255, 255));
        btnPrecio.setText("precio");
        btnPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPrecio.addActionListener(this::btnPrecioActionPerformed);

        jSeparator1.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator1.setForeground(new java.awt.Color(225, 6, 0));

        jSeparator3.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator3.setForeground(new java.awt.Color(225, 6, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator4.setForeground(new java.awt.Color(225, 6, 0));

        btnTemporal.setBackground(new java.awt.Color(255, 0, 51));
        btnTemporal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnTemporal.setForeground(new java.awt.Color(255, 255, 255));
        btnTemporal.setText("form CU");
        btnTemporal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTemporal.addActionListener(this::btnTemporalActionPerformed);

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial", 3, 70)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Beneficios");

        checkBoxCursos.addActionListener(this::checkBoxCursosActionPerformed);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textAreaCursos.setBackground(new java.awt.Color(18, 18, 18));
        textAreaCursos.setColumns(20);
        textAreaCursos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textAreaCursos.setForeground(new java.awt.Color(255, 255, 255));
        textAreaCursos.setRows(5);
        textAreaCursos.setText("Cursos Especiales:");
        jScrollPane1.setViewportView(textAreaCursos);

        checkBoxMusica.addActionListener(this::checkBoxMusicaActionPerformed);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textAreaMusica.setBackground(new java.awt.Color(18, 18, 18));
        textAreaMusica.setColumns(20);
        textAreaMusica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textAreaMusica.setForeground(new java.awt.Color(255, 255, 255));
        textAreaMusica.setRows(5);
        textAreaMusica.setText("Ambiente Musical Dinamico:");
        jScrollPane2.setViewportView(textAreaMusica);

        jSeparator5.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator5.setForeground(new java.awt.Color(225, 6, 0));

        checkBoxFisico.addActionListener(this::checkBoxFisicoActionPerformed);

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAreaProgresoFisico.setBackground(new java.awt.Color(18, 18, 18));
        txtAreaProgresoFisico.setColumns(20);
        txtAreaProgresoFisico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAreaProgresoFisico.setForeground(new java.awt.Color(255, 255, 255));
        txtAreaProgresoFisico.setRows(5);
        txtAreaProgresoFisico.setText("Progreso físico:");
        jScrollPane4.setViewportView(txtAreaProgresoFisico);

        jSeparator6.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator6.setForeground(new java.awt.Color(225, 6, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        checkBoxInstalaciones.addActionListener(this::checkBoxInstalacionesActionPerformed);

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textAreaInstalaciones.setBackground(new java.awt.Color(18, 18, 18));
        textAreaInstalaciones.setColumns(20);
        textAreaInstalaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textAreaInstalaciones.setForeground(new java.awt.Color(255, 255, 255));
        textAreaInstalaciones.setRows(5);
        textAreaInstalaciones.setText("Acceso a nuestras instalaciones:");
        jScrollPane5.setViewportView(textAreaInstalaciones);

        checkBoxNutricion.addActionListener(this::checkBoxNutricionActionPerformed);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textAreaCentroNutricion.setBackground(new java.awt.Color(18, 18, 18));
        textAreaCentroNutricion.setColumns(20);
        textAreaCentroNutricion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textAreaCentroNutricion.setForeground(new java.awt.Color(255, 255, 255));
        textAreaCentroNutricion.setRows(5);
        textAreaCentroNutricion.setText("Centro de Nutrición:");
        jScrollPane3.setViewportView(textAreaCentroNutricion);

        lblPrecio.setBackground(new java.awt.Color(255, 255, 255));
        lblPrecio.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio.setText("Todo esto a tan solo!!!:");

        ComboBoxMembresia.setBackground(new java.awt.Color(44, 44, 44));
        ComboBoxMembresia.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        ComboBoxMembresia.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxMembresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bronce", "Plata", "Oro" }));
        ComboBoxMembresia.addActionListener(this::ComboBoxMembresiaActionPerformed);

        btnSuscribirse1.setBackground(new java.awt.Color(255, 0, 51));
        btnSuscribirse1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSuscribirse1.setForeground(new java.awt.Color(255, 255, 255));
        btnSuscribirse1.setText("Suscribirse");
        btnSuscribirse1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSuscribirse1.addActionListener(this::btnSuscribirse1ActionPerformed);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(checkBoxInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(checkBoxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnSuscribirse1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(checkBoxFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(650, 650, 650)
                .addComponent(checkBoxNutricion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(680, 680, 680)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(btnPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(ComboBoxMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(930, 930, 930)
                .addComponent(checkBoxMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(720, 720, 720)
                .addComponent(btnTemporal, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(checkBoxInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(btnSuscribirse1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(checkBoxFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(checkBoxNutricion))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(btnPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(ComboBoxMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(checkBoxMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(btnTemporal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecioActionPerformed

    }//GEN-LAST:event_btnPrecioActionPerformed

    private void btnTemporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemporalActionPerformed
        //temporal
        control.navegarBienvenida();
    }//GEN-LAST:event_btnTemporalActionPerformed

    private void checkBoxNutricionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxNutricionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxNutricionActionPerformed

    private void checkBoxInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxInstalacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxInstalacionesActionPerformed

    private void checkBoxFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxFisicoActionPerformed

    private void checkBoxMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxMusicaActionPerformed

    private void checkBoxCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxCursosActionPerformed

    private void ComboBoxMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMembresiaActionPerformed
        this.actualizarBeneficios();
    }//GEN-LAST:event_ComboBoxMembresiaActionPerformed

    private void btnSuscribirse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuscribirse1ActionPerformed
        control.navegarMetodosPago();
    }//GEN-LAST:event_btnSuscribirse1ActionPerformed

    private void actualizarBeneficios() {
        String membresia = (String) ComboBoxMembresia.getSelectedItem();

        checkBoxInstalaciones.setSelected(true);
        checkBoxNutricion.setSelected(false);
        checkBoxMusica.setSelected(false);
        checkBoxFisico.setSelected(false);
        checkBoxCursos.setSelected(false);

        switch (membresia) {
            case "Oro":
                checkBoxCursos.setSelected(true);
                checkBoxFisico.setSelected(true);

            case "Plata":
                checkBoxNutricion.setSelected(true);
                checkBoxMusica.setSelected(true);

                break;
            case "Bronce":
                break;
        }

        if (membresia.equals("Oro")) {
            btnPrecio.setText("$750");
        } else if (membresia.equals("Plata")) {
            btnPrecio.setText("$500");
        } else {
            btnPrecio.setText("$300");
        }
    }
    
    private void setearEditablesFalsosCheckBox(){
        checkBoxCursos.setEnabled(false);
        checkBoxFisico.setEnabled(false);
        checkBoxInstalaciones.setEnabled(false);
        checkBoxMusica.setEnabled(false);
        checkBoxNutricion.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxMembresia;
    private javax.swing.JButton btnPrecio;
    private javax.swing.JButton btnSuscribirse1;
    private javax.swing.JButton btnTemporal;
    private javax.swing.JCheckBox checkBoxCursos;
    private javax.swing.JCheckBox checkBoxFisico;
    private javax.swing.JCheckBox checkBoxInstalaciones;
    private javax.swing.JCheckBox checkBoxMusica;
    private javax.swing.JCheckBox checkBoxNutricion;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea textAreaCentroNutricion;
    private javax.swing.JTextArea textAreaCursos;
    private javax.swing.JTextArea textAreaInstalaciones;
    private javax.swing.JTextArea textAreaMusica;
    private javax.swing.JTextArea txtAreaProgresoFisico;
    // End of variables declaration//GEN-END:variables
}
